export const projectData = [
  {
    projectTitle: "WirTreffenFreunde",
    projectImage: "images/WTF-screenshot.png",
    techStack: "images/WTF_techStack.png",
    summary: "App for friends to find middle point to meet",
    link: "",
    frontendRepo: "https://github.com/wirTreffenFreunde/wtf-frontend",
    backendRepo: "https://github.com/wirTreffenFreunde/wtf-backend",
    team: [
      {
        name: "Dr. Mamuna Anwar",
        github: "http://github.com/mamuna36",
        linkedIn: "https://www.linkedin.com/in/mamunaanwar",
        email: "mamuna.anwar@gmail.com",
        id: 0,
      },
      {
        name: "Ilona Avdiushkina",
        github: "http://github.com/vbldra",
        linkedIn: "https://www.linkedin.com/in/avdiushkina/",
        email: "ilona.avdiushkina@gmail.com",
        id: 1,
      },
      {
        name: "Raluca Stefania",
        github: "http://github.com/ralucastefania",
        linkedIn:
          "https://www.linkedin.com/in/raluca-stefania-bochis-853abb1a5/",
        email: "",
        id: 2,
      },
      {
        name: "Dan Turebekov",
        github: "http://github.com/boturdan",
        linkedIn: "",
        email: "",
        id: 3,
      },
      {
        name: "Florian Bocu",
        github: "https://github.com/florian777b",
        linkedIn: "https://www.linkedin.com/in/florian-bocu-b52448203",
        email: "",
        id: 4,
      },
    ],
  },
  {
    projectTitle: "Mindchase-Website",
    projectImage: "",
    summary: "",
    techStack: "/images/mindchase_techStack.png",
    link: "",
    frontendRepo: "",
    backendRepo: "",
    team: [
      {
        name: "Agata Bernat",
        github: "http://github.com/Agata-Bernat",
        linkedIn: "http://linkedin.com/in/agata-bernat",
        email: "agata.bernat.art@gmail.com",
        id: 0,
      },
      {
        name: "Doven Obertinka",
        github: "http://github.com/Doven-Obertinca",
        linkedIn: "http://linkedin.com/in/doven-obertinca-8b08971b2/",
        email: "doven.obertinca@gmail.com",
        id: 1,
      },
      {
        name: "Paul Bongers",
        github: "http://github.com/cunning-weasel",
        linkedIn: "http://linkedin.com/in/paul-bongers",
        email: "paulbongers22@gmail.com",
        id: 2,
      },
    ],
  },
  {
    projectTitle: "mindchase-digital-campus",
    projectImage: "",
    techStack: "images/mindchase_techStack.png",
    summary: "",
    link: "",
    frontendRepo: "",
    backendRepo: "",
    team: [
      {
        name: "Mohammad basem Karah bi",
        github: "http://github.com/basimkarhabi",
        linkedIn: "http://linkedin.com/in/mohammad-basem-karha-bi-b1a14611a",
        email: "basim.karhabi@gmail.com",
        id: 0,
      },
      {
        name: "Ibrahim Andraws",
        github: "http://github.com/Iandraws",
        linkedIn: "http://linkedin.com/in/abraham-andraous-703251211",
        email: "abrahamxman2@gmail.com",
        id: 1,
      },
      {
        name: "Fuad Abdullah",
        github: "https://github.com/fuad221",
        linkedIn: "https://www.linkedin.com/in/fuad02/",
        email: "fuad221@outlook.com",
        id: 2,
      },
      {
        name: "Abdulkader Jabboulieh",
        github: "http://github.com/abdojabboulie",
        linkedIn: "http://linkedin.com/in/abdo-jabboulieh-668433210",
        email: "abdojabboulie@gmail.com",
        id: 3,
      },
    ],
  },
  {
    projectTitle: "YourMarket",
    projectImage: "/images/mohamed_yahya_ecommerce_project.png",
    summary: "This is an e-commerce app.",
    link: "",
    frontendRepo: "https://github.com/mohamed-yahya-zakria/frontend",
    backendRepo: "https://github.com/mohamed-yahya-zakria/backend",
    team: [
      {
        name: "Mohamed Yahya",
        github: "https://github.com/mohamed-yahya-zakria",
        linkedIn: "https://www.linkedin.com/in/mohamed-yahya-zakaria/",
        email: "mohamed.yahya.zakria73@gmail.com",
        id: 0,
      },
    ],
  },
  {
    projectTitle: "Market Royal",
    projectImage: "/images/nour_din_e_commerce_project.png",
    summary:
      "online Market like eBay you can sell and buy products and mack your offer and bids",
    link: "",
    frontendRepo: "",
    backendRepo: "",
    team: [
      {
        name: "Nour eddin",
        github: "https://github.com/Nour-jin",
        linkedIn: "https://www.linkedin.com/in/nour-eddin-nasrallah-264737218",
        email: "nour.eddin.jin@outlook.com",
        id: 0,
      },
    ],
  },
];
